// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnynQBg-ZpkFlj2C0Ipf6fWXmJ6ASyE_8',
    appId: '1:1070524752875:web:da59568e79922494f52fae',
    messagingSenderId: '1070524752875',
    projectId: 'ayurdb-2094d',
    authDomain: 'ayurdb-2094d.firebaseapp.com',
    databaseURL: 'https://ayurdb-2094d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ayurdb-2094d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWyYL1GiFHtGFTLlsoFBUD3EWDYMBTHyY',
    appId: '1:1070524752875:android:1ce5e3edbdabec2bf52fae',
    messagingSenderId: '1070524752875',
    projectId: 'ayurdb-2094d',
    databaseURL: 'https://ayurdb-2094d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ayurdb-2094d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0fMZD7j-WT76KOOr8nadNFV9dYgX7twU',
    appId: '1:1070524752875:ios:40386a3874a8c64ff52fae',
    messagingSenderId: '1070524752875',
    projectId: 'ayurdb-2094d',
    databaseURL: 'https://ayurdb-2094d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ayurdb-2094d.appspot.com',
    iosClientId: '1070524752875-955pj70msuhcmu44hu8eh2288hhvfloq.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayurLeaf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0fMZD7j-WT76KOOr8nadNFV9dYgX7twU',
    appId: '1:1070524752875:ios:e70ec26f6b4c97a9f52fae',
    messagingSenderId: '1070524752875',
    projectId: 'ayurdb-2094d',
    databaseURL: 'https://ayurdb-2094d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ayurdb-2094d.appspot.com',
    iosClientId: '1070524752875-qtm1scl56oeel9nb4m3lipia6eumha1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayurLeaf.RunnerTests',
  );
}
